import {useState} from 'react';import {api} from './api';
type Setup={id:string;plan:{symbol:string;direction:string;entryLow:number;entryHigh:number;stop:number;target:number};observation:{state:string;reason?:string;favorableR?:number|null;adverseR?:number|null};last_checked_at:string|null;last_error:string|null;provider:string|null;provider_instrument:string|null};
type Summary={sampleCount:number;counts:Record<string,number>;entryTouchCount:number;terminalReferenceCount:number;favorableRObserved:{count:number;mean:number|null;max:number|null};adverseRObserved:{count:number;mean:number|null;max:number|null};winRate:null;expectancy:null;profitFactor:null;explanation:string};
export default function MonitorPanel(){
 const [rows,setRows]=useState<Setup[]>([]),[summary,setSummary]=useState<Summary|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[loaded,setLoaded]=useState(false);
 async function refresh(check=false){setBusy(true);setError('');try{if(check)await api.post('/api/monitor/check',{});const data=(await api.get('/api/monitor')).data;setRows(data.setups);setSummary(data.summary);setLoaded(true);}catch(e){setError(e instanceof Error?e.message:'Monitoring unavailable');}finally{setBusy(false);}}
 return <main className='shell'><section className='scanner-card auth-panel'><div className='eyebrow'>REAL CLOSED-CANDLE OBSERVATIONS</div><h1>Forward monitor</h1>
  <p>Track whether future reference candles touch a saved entry zone, stop or target. No fill, spread, slippage or P&L is assumed.</p><div className='event-actions'><button disabled={busy} onClick={()=>void refresh()}>Load observations</button><button disabled={busy} onClick={()=>void refresh(true)}>Check markets now</button></div>
  {busy&&<p role='status'>Checking…</p>}{error&&<p role='alert'>{error}</p>}
  {loaded&&summary&&<article className='journal-item'><h2>Observation summary</h2><p>{summary.sampleCount} registered · {summary.entryTouchCount} entry-zone touches · {summary.terminalReferenceCount} terminal reference touches</p>
   <p>States: {Object.entries(summary.counts).map(([k,v])=>k.replaceAll('_',' ')+' '+v).join(' · ')}</p>
   <p>Favorable R observed: mean {summary.favorableRObserved.mean??'—'} · max {summary.favorableRObserved.max??'—'}<br/>Adverse R observed: mean {summary.adverseRObserved.mean??'—'} · max {summary.adverseRObserved.max??'—'}</p><small>{summary.explanation}</small></article>}
  {loaded&&rows.length===0&&<p>No monitored setups. Register a supported scenario from your journal.</p>}
  {rows.map(row=><article className='journal-item' key={row.id}><h2>{row.plan.symbol} · {row.plan.direction}</h2><strong>{row.observation.state.replaceAll('_',' ')}</strong><p>Entry zone: {row.plan.entryLow}–{row.plan.entryHigh}<br/>Stop reference: {row.plan.stop} · Target reference: {row.plan.target}</p><p>{row.observation.reason||'Waiting for the first data check.'}</p>{row.last_error&&<p role='status'>Data blocked: {row.last_error.replaceAll('_',' ')}</p>}<p>Source: {row.provider||'Not observed'} {row.provider_instrument||''}</p><small>{row.last_checked_at?'Last check: '+new Date(row.last_checked_at).toLocaleString():'No completed check'}</small></article>)}
  <p>Unknown intrabar ordering is marked ambiguous. Data gaps and stale candles block conclusions.</p></section></main>;
}
